language: node_js
node_js:
  - "4.1.x"
  - "iojs"
services:
  - mongodb
  - redis-server
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
env:
  - dev=true
service_name: travis-pro
repo_token: C66RFjqQ1uG6Z43TJB7gmiyywUjL3dhpZ
script: make test-cov
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

#before_install:
#  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
#env:
# - LAIKA_OPTIONS="-t 5000"