sudo: false

language: node_js

env:
  - CXX=g++-4.8 NODE_ENV=test
node_js:
  - 'iojs'
  - '4'
  - '5'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - mongodb
  - redis

before_install:
  - $CXX --version

script: make test

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

service_name: travis-pro
repo_token: C66RFjqQ1uG6Z43TJB7gmiyywUjL3dhpZ
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
